[input]
html_selector = ".post-content"
exclude_html_selector = "script, pre, .toc-nav, .math"
minimum_index_ideographic_substring_length = 2
base_directory = "output"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "pages/shan-qiang-bian.html"
url = "/pages/shan-qiang-bian.html"
title = "山墙边"

[[input.files]]
path = "zai-lu-shang/2023-12-31-2023-summary.html"
url = "/zai-lu-shang/2023-12-31-2023-summary.html"
title = "忙忙碌碌中匆匆过眼我的 2023 年"

[[input.files]]
path = "sui-sui-nian/2023-11-17-deploy-backblaze-image-hosting.html"
url = "/sui-sui-nian/2023-11-17-deploy-backblaze-image-hosting.html"
title = "Cloudflare + Backblaze 实现免费的博客图床方案"

[[input.files]]
path = "sui-sui-nian/2023-11-11-necessary-config-of-new-server.html"
url = "/sui-sui-nian/2023-11-11-necessary-config-of-new-server.html"
title = "新服务器必做的基本设置——服务器迁移之记录"

[[input.files]]
path = "sui-sui-nian/2023-10-31-cloudflare-dns-of-blog.html"
url = "/sui-sui-nian/2023-10-31-cloudflare-dns-of-blog.html"
title = "把博客站点交给了 Cloudflare 托管"

[[input.files]]
path = "sui-sui-nian/2023-09-14-rime-script-simple-tutorial.html"
url = "/sui-sui-nian/2023-09-14-rime-script-simple-tutorial.html"
title = "RIME 脚本食用方法举隅：以输入苏州码为例"

[[input.files]]
path = "sui-sui-nian/2023-08-05-connect-docker-container-by-pycharm.html"
url = "/sui-sui-nian/2023-08-05-connect-docker-container-by-pycharm.html"
title = "通过 SSH 在 Pycharm 上使用 Docker 容器中的 Python 解释器"

[[input.files]]
path = "sui-sui-nian/2023-07-28-build-arm-docker-image-on-x86.html"
url = "/sui-sui-nian/2023-07-28-build-arm-docker-image-on-x86.html"
title = "如何在 X86 设备上使用 Docker 构建 ARM 镜像"

[[input.files]]
path = "sui-sui-nian/2023-06-23-summary-doi.org/10.1038/s42256-023-00647-z.html"
url = "/sui-sui-nian/2023-06-23-summary-doi.org/10.1038/s42256-023-00647-z.html"
title = "文献总结｜结构诱导的预训练"

[[input.files]]
path = "sui-sui-nian/2023-06-09-summary-doi.org/10.1007/978-3-031-29119-7_6.html"
url = "/sui-sui-nian/2023-06-09-summary-doi.org/10.1007/978-3-031-29119-7_6.html"
title = "文献总结｜MTGL-ADMET：一种通过地位理论与最大流增强并用于 ADMET 预测的多任务图学习框架"

[[input.files]]
path = "sui-sui-nian/2023-06-02-summary-doi.org/10.48550/arXiv.2303.03951.html"
url = "/sui-sui-nian/2023-06-02-summary-doi.org/10.48550/arXiv.2303.03951.html"
title = "文献总结｜探测图表示"

[[input.files]]
path = "zai-lu-shang/2023-05-30-new-calligraphy-paper.html"
url = "/zai-lu-shang/2023-05-30-new-calligraphy-paper.html"
title = "四月十二奉新纸一试"

[[input.files]]
path = "sui-sui-nian/2023-05-27-summary-doi.org/10.1038/s42256-023-00639-z.html"
url = "/sui-sui-nian/2023-05-27-summary-doi.org/10.1038/s42256-023-00639-z.html"
title = "文献总结｜可以同时完成分子语言序列回归和生成的 Regression Transformer"

[[input.files]]
path = "zai-lu-shang/2023-05-22-wander-in-old-book-shop.html"
url = "/zai-lu-shang/2023-05-22-wander-in-old-book-shop.html"
title = "旧书市场淘书记"

[[input.files]]
path = "sui-sui-nian/2023-05-19-summary-doi.org/10.48550/arXiv.2203.10446.html"
url = "/sui-sui-nian/2023-05-19-summary-doi.org/10.48550/arXiv.2203.10446.html"
title = "文献总结｜一种用于基于结构药物设计的 3D 生成模型"

[[input.files]]
path = "sui-sui-nian/2023-05-13-summary-doi.org/10.1186/s13321-023-00713-z.html"
url = "/sui-sui-nian/2023-05-13-summary-doi.org/10.1186/s13321-023-00713-z.html"
title = "文献总结｜对编码器-解码器模型学习过程中化学结构识别的研究"

[[input.files]]
path = "sui-sui-nian/2023-04-28-summary-doi.org/10.1021/acs.jcim.2c01618.html"
url = "/sui-sui-nian/2023-04-28-summary-doi.org/10.1021/acs.jcim.2c01618.html"
title = "文献总结｜我们能用 Transformer 模型快速学会「翻译」活性分子吗？"

[[input.files]]
path = "zai-lu-shang/2023-04-27-crabapple-of-tianjin.html"
url = "/zai-lu-shang/2023-04-27-crabapple-of-tianjin.html"
title = "津城海棠"

[[input.files]]
path = "sui-sui-nian/2023-04-22-summary-openreview.html"
url = "/sui-sui-nian/2023-04-22-summary-openreview.html"
title = "文献总结｜使用上下文增强的分子表示提升少样本药物发现的效果"

[[input.files]]
path = "sui-sui-nian/2023-04-21-transformer-from-scratch.html"
url = "/sui-sui-nian/2023-04-21-transformer-from-scratch.html"
title = "从零起步的 Transformer 与代码拆解"

[[input.files]]
path = "sui-sui-nian/2023-04-15-summary-doi.org/10.1021/acs.jmedchem.2c01787.html"
url = "/sui-sui-nian/2023-04-15-summary-doi.org/10.1021/acs.jmedchem.2c01787.html"
title = "文献总结｜药物发现中的匹配分子对分析：方法与当前应用"

[[input.files]]
path = "zai-lu-shang/2023-04-11-my-gardening-plan.html"
url = "/zai-lu-shang/2023-04-11-my-gardening-plan.html"
title = "我的 2023 年春播计划"

[[input.files]]
path = "sui-sui-nian/2023-04-06-summary-doi.org/10.1186/s13321-023-00694-z.html"
url = "/sui-sui-nian/2023-04-06-summary-doi.org/10.1186/s13321-023-00694-z.html"
title = "文献总结｜DrugEx v3：使用基于图 Transformer 的强化学习进行以分子骨架为约束的药物设计"

[[input.files]]
path = "sui-sui-nian/2023-04-01-summary-doi.org/10.1186/s13321-023-00702-2.html"
url = "/sui-sui-nian/2023-04-01-summary-doi.org/10.1186/s13321-023-00702-2.html"
title = "文献总结｜用于从蛋白序列进行药物设计的深度生成模型"

[[input.files]]
path = "gu-zhi-dui/2023-03-30-book-chinese-narratology.html"
url = "/gu-zhi-dui/2023-03-30-book-chinese-narratology.html"
title = "在明清小说中索隐：读《中国叙事学》"

[[input.files]]
path = "sui-sui-nian/2023-03-25-summary-doi.org/10.48550/arXiv.2302.01129.html"
url = "/sui-sui-nian/2023-03-25-summary-doi.org/10.48550/arXiv.2302.01129.html"
title = "文献总结｜通过连接感知模版挖掘实现从头生成分子"

[[input.files]]
path = "zai-lu-shang/2023-03-24-spring-trip-in-tianjin.html"
url = "/zai-lu-shang/2023-03-24-spring-trip-in-tianjin.html"
title = "春日漫步小记"

[[input.files]]
path = "sui-sui-nian/2023-03-17-summary-doi.org/10.48550/arXiv.2210.13695.html"
url = "/sui-sui-nian/2023-03-17-summary-doi.org/10.48550/arXiv.2210.13695.html"
title = "文献总结｜使用等变扩散模型进行基于结构的药物设计"

[[input.files]]
path = "sui-sui-nian/2023-03-14-deploy-pelican-search.html"
url = "/sui-sui-nian/2023-03-14-deploy-pelican-search.html"
title = "为 Pelican 博客加入搜索功能"

[[input.files]]
path = "sui-sui-nian/2023-03-11-summary-doi.org/10.48550/arXiv.2209.06158.html"
url = "/sui-sui-nian/2023-03-11-summary-doi.org/10.48550/arXiv.2209.06158.html"
title = "文献总结｜为蛋白质口袋定制分子：用于基于结构药物设计的 Transformer 分子生成方法"

[[input.files]]
path = "sui-sui-nian/2023-03-03-summary-doi.org/10.1021/acs.jcim.1c00600.html"
url = "/sui-sui-nian/2023-03-03-summary-doi.org/10.1021/acs.jcim.1c00600.html"
title = "文献总结｜MolGPT：使用 Transformer 解码器模型实现分子生成"

[[input.files]]
path = "sui-sui-nian/2023-02-25-summary-doi.org/10.1021/ci900450m.html"
url = "/sui-sui-nian/2023-02-25-summary-doi.org/10.1021/ci900450m.html"
title = "文献总结｜在大数据集中有效识别匹配分子对（MMPs）的算法"

[[input.files]]
path = "sui-sui-nian/2023-02-22-create-pelican-plugin.html"
url = "/sui-sui-nian/2023-02-22-create-pelican-plugin.html"
title = "为 Pelican 博客写插件——在文章中插入豆瓣图书"

[[input.files]]
path = "sui-sui-nian/2023-02-17-summary-doi.org/10.1038/s42256-022-00580-7.html"
url = "/sui-sui-nian/2023-02-17-summary-doi.org/10.1038/s42256-022-00580-7.html"
title = "文献总结｜通过大规模化学语言表示捕获分子结构和性质"

[[input.files]]
path = "sui-sui-nian/2023-02-13-deploy-pelican-by-nginx.html"
url = "/sui-sui-nian/2023-02-13-deploy-pelican-by-nginx.html"
title = "Pelican + Nginx 在服务器上搭载静态博客"

[[input.files]]
path = "sui-sui-nian/2023-02-11-summary-doi.org/10.1186/s13321-021-00497-0.html"
url = "/sui-sui-nian/2023-02-11-summary-doi.org/10.1186/s13321-021-00497-0.html"
title = "文献总结｜通过深度神经网络捕获化学家的直觉实现分子优化"

[[input.files]]
path = "sui-sui-nian/2023-02-08-cs224n-lecture2.html"
url = "/sui-sui-nian/2023-02-08-cs224n-lecture2.html"
title = "CS224n 自然语言处理第二节: 词向量与词义感知"

[[input.files]]
path = "sui-sui-nian/2023-02-06-rdkit-modify-substructure.html"
url = "/sui-sui-nian/2023-02-06-rdkit-modify-substructure.html"
title = "RDKit 入门：基于子结构修改分子"

[[input.files]]
path = "sui-sui-nian/2023-02-04-summary-doi.org/10.1186/s13321-022-00599-3.html"
url = "/sui-sui-nian/2023-02-04-summary-doi.org/10.1186/s13321-022-00599-3.html"
title = "文献总结｜匹配分子对以外基于 Transformer 的分子优化"

[[input.files]]
path = "sui-sui-nian/2023-01-08-summary-doi.org/10.48550/arXiv.1811.12823.html"
url = "/sui-sui-nian/2023-01-08-summary-doi.org/10.48550/arXiv.1811.12823.html"
title = "文献总结｜Molecular Sets (MOSES)：分子生成模型的评估平台"

[[input.files]]
path = "sui-sui-nian/2023-01-03-rdkit-modify-search-molecule.html"
url = "/sui-sui-nian/2023-01-03-rdkit-modify-search-molecule.html"
title = "RDKit 入门：修改分子与搜索子结构"

[[input.files]]
path = "sui-sui-nian/2022-12-25-summary-doi.org/10.1016/j.drudis.2021.05.019.html"
url = "/sui-sui-nian/2022-12-25-summary-doi.org/10.1016/j.drudis.2021.05.019.html"
title = "文献总结｜从头药物设计和生成模型"

[[input.files]]
path = "sui-sui-nian/2022-12-21-cs224n-lecture1.html"
url = "/sui-sui-nian/2022-12-21-cs224n-lecture1.html"
title = "CS224n 自然语言处理第一节：简介与词向量"

[[input.files]]
path = "sui-sui-nian/2022-12-18-summary-doi.org/10.1021/acs.jcim.2c00982.html"
url = "/sui-sui-nian/2022-12-18-summary-doi.org/10.1021/acs.jcim.2c00982.html"
title = "文献总结｜DRlinker：使用深度强化学习优化连接片段设计"

[[input.files]]
path = "sui-sui-nian/2022-12-16-opennmt-tutorial-quickstart.html"
url = "/sui-sui-nian/2022-12-16-opennmt-tutorial-quickstart.html"
title = "机器翻译框架 OpenNMT 入门：快速上手"

[[input.files]]
path = "sui-sui-nian/2022-12-11-summary-doi.org/10.1186/s13321-020-00441-8.html"
url = "/sui-sui-nian/2022-12-11-summary-doi.org/10.1186/s13321-020-00441-8.html"
title = "文献总结｜基于SMILES用于从头药物设计的深度分子骨架改造模型"

[[input.files]]
path = "sui-sui-nian/2022-12-03-summary-doi.org/10.1038/s41467-022-34692-w.html"
url = "/sui-sui-nian/2022-12-03-summary-doi.org/10.1038/s41467-022-34692-w.html"
title = "文献总结｜通过生成深度学习发现 RIPK1 抑制剂"

[[input.files]]
path = "sui-sui-nian/2022-12-01-install-cuda.html"
url = "/sui-sui-nian/2022-12-01-install-cuda.html"
title = "为深度学习环境配置 CUDA"

[[input.files]]
path = "sui-sui-nian/2022-11-25-summary-doi.org/10.1038/s42256-022-00494-4.html"
url = "/sui-sui-nian/2022-11-25-summary-doi.org/10.1038/s42256-022-00494-4.html"
title = "文献总结｜使用课程学习改进从头药物设计"

[[input.files]]
path = "sui-sui-nian/2022-11-20-summary-doi.org/10.1021/acs.jcim.1c00469.html"
url = "/sui-sui-nian/2022-11-20-summary-doi.org/10.1021/acs.jcim.1c00469.html"
title = "文献总结｜LibINVENT：可用于虚拟化合物库构建的基于反应的分子骨架改造模型"

[[input.files]]
path = "sui-sui-nian/2022-11-14-summary-doi.org/10.1039/d0sc03126g.html"
url = "/sui-sui-nian/2022-11-14-summary-doi.org/10.1039/d0sc03126g.html"
title = "文献总结｜SyntaLinker：使用 Conditional Transformer 神经网络自动连接分子片段"

[[input.files]]
path = "sui-sui-nian/2022-11-05-summary-doi.org/10.1021/acs.jcim.2c00838.html"
url = "/sui-sui-nian/2022-11-05-summary-doi.org/10.1021/acs.jcim.2c00838.html"
title = "文献总结｜使用强化学习和基于图的深度生成模型进行从头药物设计"

[[input.files]]
path = "sui-sui-nian/2022-10-29-summary-doi.org/10.1021/acs.jmedchem.2c01179.html"
url = "/sui-sui-nian/2022-10-29-summary-doi.org/10.1021/acs.jmedchem.2c01179.html"
title = "文献总结｜ChemistGA：用于实际药物发现的可合成分子生成算法"

[[input.files]]
path = "sui-sui-nian/2022-10-21-summary-doi.org/10.1186/s13321-019-0393-0.html"
url = "/sui-sui-nian/2022-10-21-summary-doi.org/10.1186/s13321-019-0393-0.html"
title = "文献总结｜通过随机化 SMILES 序列提升分子生成模型质量"

[[input.files]]
path = "sui-sui-nian/2022-10-20-rdkit-draw-molecule.html"
url = "/sui-sui-nian/2022-10-20-rdkit-draw-molecule.html"
title = "RDKit 入门：绘制分子图像"

[[input.files]]
path = "sui-sui-nian/2022-10-18-rdkit-import-export-file.html"
url = "/sui-sui-nian/2022-10-18-rdkit-import-export-file.html"
title = "RDKit 入门：文件的导入与导出"

[[input.files]]
path = "sui-sui-nian/2022-10-15-summary-doi.org/10.1021/acs.jcim.0c00915.html"
url = "/sui-sui-nian/2022-10-15-summary-doi.org/10.1021/acs.jcim.0c00915.html"
title = "文献总结｜REINVENT 2.0：用于从头药物设计的 AI 工具"

[[input.files]]
path = "sui-sui-nian/2022-10-08-summary-doi.org/10.1038/s42256-021-00403-1.html"
url = "/sui-sui-nian/2022-10-08-summary-doi.org/10.1038/s42256-021-00403-1.html"
title = "文献总结｜基于 Conditional Transformer、知识蒸馏与强化学习的多约束分子生成"

[[input.files]]
path = "sui-sui-nian/2022-09-30-summary-doi.org/10.1021/acscentsci.7b00512.html"
url = "/sui-sui-nian/2022-09-30-summary-doi.org/10.1021/acscentsci.7b00512.html"
title = "文献总结｜使用循环神经网络为药物发现生成指定的分子库"

[[input.files]]
path = "sui-sui-nian/2022-09-27-generate-ppt-by-marp.html"
url = "/sui-sui-nian/2022-09-27-generate-ppt-by-marp.html"
title = "用 Markdown 创作 pptx 的尝试"

[[input.files]]
path = "sui-sui-nian/2022-09-21-summary-doi.org/10.1016/j.sbi.2021.10.001.html"
url = "/sui-sui-nian/2022-09-21-summary-doi.org/10.1016/j.sbi.2021.10.001.html"
title = "文献总结｜从头药物设计中的深度学习方法"

[[input.files]]
path = "sui-sui-nian/2022-09-16-statistical-learning-chapter7.html"
url = "/sui-sui-nian/2022-09-16-statistical-learning-chapter7.html"
title = "《统计学习方法》第七章：支持向量机"

[[input.files]]
path = "sui-sui-nian/2022-09-09-statistical-learning-chapter6.html"
url = "/sui-sui-nian/2022-09-09-statistical-learning-chapter6.html"
title = "《统计学习方法》第六章：逻辑斯谛回归与最大熵模型"

[[input.files]]
path = "sui-sui-nian/2022-09-06-dns-forbidden-of-github-pages.html"
url = "/sui-sui-nian/2022-09-06-dns-forbidden-of-github-pages.html"
title = "国内部分网络无法访问 githui.io 的解决方案"

[[input.files]]
path = "sui-sui-nian/2022-09-05-function-drawer.html"
url = "/sui-sui-nian/2022-09-05-function-drawer.html"
title = "函数绘图工具的选择"

[[input.files]]
path = "gu-zhi-dui/2022-08-31-hokciu-word-collect.html"
url = "/gu-zhi-dui/2022-08-31-hokciu-word-collect.html"
title = "詞藪"

[[input.files]]
path = "sui-sui-nian/2022-08-23-statistical-learning-chapter5.html"
url = "/sui-sui-nian/2022-08-23-statistical-learning-chapter5.html"
title = "《统计学习方法》第五章：决策树"

[[input.files]]
path = "sui-sui-nian/2022-08-17-pelican-lightbox.html"
url = "/sui-sui-nian/2022-08-17-pelican-lightbox.html"
title = "为 Pelican 博客设置 Lightbox 效果"

[[input.files]]
path = "sui-sui-nian/2022-08-14-prettymaps-generate-maps.html"
url = "/sui-sui-nian/2022-08-14-prettymaps-generate-maps.html"
title = "使用 prettymaps 生成精美地图"

[[input.files]]
path = "sui-sui-nian/2022-08-11-prettymaps-install.html"
url = "/sui-sui-nian/2022-08-11-prettymaps-install.html"
title = "在 Windows 安装 prettymaps 的踩坑实录"

[[input.files]]
path = "sui-sui-nian/2022-08-05-statistical-learning-chapter4.html"
url = "/sui-sui-nian/2022-08-05-statistical-learning-chapter4.html"
title = "《统计学习方法》第四章：朴素贝叶斯法"

[[input.files]]
path = "sui-sui-nian/2022-08-02-statistical-learning-chapter3.html"
url = "/sui-sui-nian/2022-08-02-statistical-learning-chapter3.html"
title = "《统计学习方法》第三章：k 近邻法"

[[input.files]]
path = "sui-sui-nian/2022-07-27-statistical-learning-chapter2.html"
url = "/sui-sui-nian/2022-07-27-statistical-learning-chapter2.html"
title = "《统计学习方法》第二章：感知机"

[[input.files]]
path = "sui-sui-nian/2022-07-21-statistical-learning-chapter1.html"
url = "/sui-sui-nian/2022-07-21-statistical-learning-chapter1.html"
title = "《统计学习方法》第一章：概论"

[[input.files]]
path = "sui-sui-nian/2022-07-14-onedrive-as-image-host.html"
url = "/sui-sui-nian/2022-07-14-onedrive-as-image-host.html"
title = "在 Linux 上使用 OneDrive 作为博客图床"

[[input.files]]
path = "sui-sui-nian/2022-07-12-pelican-to-publish.html"
url = "/sui-sui-nian/2022-07-12-pelican-to-publish.html"
title = "使用 Pelican 发布文章的流程"

[output]
excerpts_per_result = 0
